# ワークフローの名前
name: Collect New Corporations Daily

# ワークフローが実行されるトリガー
on:
  workflow_dispatch: # 手動で実行できるようにする
  schedule:
    # 毎日AM2:00 (JST) に実行 (UTCでは前日の17:00)
    - cron: '0 17 * * *'

# 実行されるジョブを定義
jobs:
  run-batch-job:
    # ジョブを実行する仮想環境の種類
    runs-on: ubuntu-latest

    # ジョブのステップ
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. .envファイルを作成
      # GitHubのSecretsに保存した秘密情報を読み込んで、.envファイルに書き出す
      - name: Create .env file
        run: |
          echo "GBIZINFO_API_KEY=${{ secrets.GBIZINFO_API_KEY }}" >> ./batch/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ./batch/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> ./batch/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./batch/.env
          echo "DB_HOST=db" >> ./batch/.env
          echo "DB_PORT=5432" >> ./batch/.env
          echo "DB_NAME=${{ secrets.POSTGRES_DB }}" >> ./batch/.env
          echo "DB_USER=${{ secrets.POSTGRES_USER }}" >> ./batch/.env
          echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./batch/.env

      # 3. Docker Composeでバッチ処理を実行
      - name: Run batch job
        run: docker-compose run --rm batch
